import { corsHeaders, db, json, parseBody, requireDashboardAuth, invoke } from '../_shared/command.ts';

type J=Record<string,unknown>;const rec=(v:unknown):J=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:{};const txt=(v:unknown)=>typeof v==='string'?v.trim():v==null?'':String(v);
const GENERAL_DISCOVERY=new Set(['BUSINESS_DEVELOPMENT_DISCOVERY','OPPORTUNITY_PARTNER_DISCOVERY','INSTITUTIONAL_BUYER_DISCOVERY']);

async function createRun(type:any,missionType:string,missionName:string,stateCode:string|null,agent:string){const now=new Date().toISOString();return (await db('command_runs',{method:'POST',body:JSON.stringify({idempotency_key:`ecc:${missionType}:${stateCode||'ENTERPRISE'}:${crypto.randomUUID()}`,status:'running',current_stage:'INITIALIZING',definition_id:type.default_command_definition_id,aadp_state:'RUNNING',mission_type_key:missionType,mission_name:missionName,state_code:stateCode,assigned_agent:agent,last_activity_at:now,progress_mode:'STAGE',progress_value:5,execution_evidence:{source:'EXECUTIVE_COMMAND_CENTER',operator_authorized:true}})}))[0];}
async function createMission(run:any,missionType:string,missionName:string,stateCode:string|null,agent:string){const now=new Date().toISOString();return (await db('command_missions',{method:'POST',body:JSON.stringify({mission_type_key:missionType,mission_name:missionName,state_code:stateCode,assigned_agent:agent,authorization_state:'AUTHORIZED',authorization_required:true,authorized_at:now,command_run_id:run.id,mission_config:{source:'EXECUTIVE_COMMAND_CENTER',defaults_resolved:true}})}))[0];}
async function audit(mission:any,run:any,missionType:string,stateCode:string|null,execution:unknown){await db('command_audit_log',{method:'POST',body:JSON.stringify({entity_type:'MISSION',entity_id:mission.id,action_type:'MISSION_AUTHORIZED',actor_type:'OPERATOR',command_run_id:run.id,previous_state:{},new_state:{authorization_state:'AUTHORIZED',execution},reason:'Operator authorized mission from Executive Command Center',evidence:{mission_type:missionType,state_code:stateCode}})});}

async function acquisition(type:any,missionType:string,missionName:string,stateCode:string,agent:string){
  const registry=await db(`publisher_registry?state_code=eq.${stateCode}&verified=eq.true&select=publisher_name`);const allowed=new Set((registry||[]).map((x:any)=>txt(x.publisher_name).toLowerCase()));
  const assignments=await db('publisher_assignments?status=eq.READY&select=*&order=updated_at.desc');const assignment=(assignments||[]).find((x:any)=>allowed.has(txt(x.publisher_name).toLowerCase()));
  if(!assignment)return {error:`No READY verified publisher assignment is available for ${stateCode}. Run Publisher Discovery / onboarding first.`,status:409};
  const idem=`ecc-acquisition:${stateCode}:${assignment.id}:${new Date().toISOString().slice(0,10)}`;const execution=await invoke('command-aadp-run',{assignment_id:assignment.id,idempotency_key:idem});
  const runId=txt(rec(execution).run_id);const rows=await db(`command_runs?id=eq.${runId}&select=*`);const run=rows?.[0];if(!run)throw new Error('AADP runtime did not return an authoritative command run.');
  await db(`command_runs?id=eq.${run.id}`,{method:'PATCH',body:JSON.stringify({mission_type_key:missionType,mission_name:missionName,state_code:stateCode,assigned_agent:agent,progress_mode:'STAGE',progress_value:5,last_activity_at:new Date().toISOString(),execution_evidence:{source:'EXECUTIVE_COMMAND_CENTER',operator_authorized:true,assignment_id:assignment.id,publisher_name:assignment.publisher_name}})});
  const mission=await createMission(run,missionType,missionName,stateCode,agent);await audit(mission,run,missionType,stateCode,execution);return {mission,run:{...run,mission_type_key:missionType,mission_name:missionName,state_code:stateCode,assigned_agent:agent},execution};
}

async function publisher(type:any,missionType:string,missionName:string,stateCode:string,agent:string){const run=await createRun(type,missionType,missionName,stateCode,agent);const mission=await createMission(run,missionType,missionName,stateCode,agent);try{const execution=await invoke('command-aadp-publisher-discovery',{state_code:stateCode,command_run_id:run.id,mission_name:missionName,discovery_scope:'STATEWIDE_ALL',organization_types:['State Agencies','Counties','Cities / Municipalities','Universities','Community Colleges','School Districts','Transportation Authorities','Public Utilities','Water Districts','Special Districts','Public Authorities','Independent Agencies','Other Public Procurement Publishers'],provider:'system_default',operator:'Executive Command Center',notes:'Authorized through simplified Executive Mission Control.',autonomous_research:true});await db(`command_runs?id=eq.${run.id}`,{method:'PATCH',body:JSON.stringify({current_stage:rec(execution).current_stage||'PUBLISHER_DISCOVERY_STARTED',last_activity_at:new Date().toISOString(),progress_value:10,execution_evidence:{source:'EXECUTIVE_COMMAND_CENTER',operator_authorized:true,discovery_run_id:rec(execution).discovery_run_id}})});await audit(mission,run,missionType,stateCode,execution);return {mission,run,execution};}catch(e){await db(`command_runs?id=eq.${run.id}`,{method:'PATCH',body:JSON.stringify({status:'failed',aadp_state:'FAILED',current_stage:'START_FAILED',failure_count:1,action_required:true,last_activity_at:new Date().toISOString(),result_summary:e instanceof Error?e.message:String(e)})});throw e;}}

async function genericDiscovery(type:any,missionType:string,missionName:string,stateCode:string,agent:string){const run=await createRun(type,missionType,missionName,stateCode,agent);const mission=await createMission(run,missionType,missionName,stateCode,agent);try{const execution=await invoke('command-research-discovery',{command_run_id:run.id,mission_type_key:missionType,mission_name:missionName,state_code:stateCode,assigned_agent:agent});await audit(mission,run,missionType,stateCode,execution);return {mission,run,execution};}catch(e){await db(`command_runs?id=eq.${run.id}`,{method:'PATCH',body:JSON.stringify({status:'failed',aadp_state:'FAILED',current_stage:'START_FAILED',failure_count:1,action_required:true,last_activity_at:new Date().toISOString(),result_summary:e instanceof Error?e.message:String(e)})});throw e;}}

async function stateMission(type:any,missionType:string,missionName:string,stateCode:string,agent:string){const run=await createRun(type,missionType,missionName,stateCode,agent);const mission=await createMission(run,missionType,missionName,stateCode,agent);const caps=await db(`state_capability_status?state_code=eq.${stateCode}&select=*`);const order=['PUBLISHER_DISCOVERY','ACQUISITION_DISCOVERY','BUSINESS_DEVELOPMENT_DISCOVERY','OPPORTUNITY_PARTNER_DISCOVERY','INSTITUTIONAL_BUYER_DISCOVERY'];let next:string|null=null;for(const key of order){const c=(caps||[]).find((x:any)=>txt(x.mission_type_key)===key);if(!c||c.evidence_sufficient!==true||!['READY','OPERATIONAL','COMPLETE'].includes(txt(c.readiness_status).toUpperCase())){next=key;break;}}
  const now=new Date().toISOString();await db(`state_inventory?state_code=eq.${stateCode}`,{method:'PATCH',body:JSON.stringify({inventory_status:next?'ONBOARDING':'OPERATIONAL',overall_readiness:next?'INCOMPLETE':'READY',current_mission_id:null,last_mission_id:run.id,next_recommended_mission_type:next,onboarding_started_at:next?now:null,operational_at:next?null:now,last_evaluated_at:now,updated_at:now,evidence:{evaluated_by:'STATE_MISSION',capabilities_evaluated:(caps||[]).length,next_recommended_mission_type:next}})});
  if(next){const existing=await db(`command_recommendations?state_code=eq.${stateCode}&recommended_mission_type_key=eq.${next}&recommendation_status=eq.PROPOSED&select=id`);if(!existing.length)await db('command_recommendations',{method:'POST',body:JSON.stringify({state_code:stateCode,recommended_mission_type_key:next,reason:'Next unresolved state capability based on authoritative capability evidence.',rationale:{source:'STATE_MISSION',operator_authorization_required:true},recommendation_status:'PROPOSED',generated_at:now})});}
  await db(`command_runs?id=eq.${run.id}`,{method:'PATCH',body:JSON.stringify({status:'completed',aadp_state:'COMPLETED',current_stage:null,progress_value:100,last_activity_at:now,completed_at:now,action_required:false,result_summary:next?`State evaluated. Next recommended mission: ${next}.`:'State capability evidence supports OPERATIONAL status.',execution_evidence:{source:'STATE_MISSION',next_recommended_mission_type:next,child_mission_auto_authorized:false}})});await audit(mission,run,missionType,stateCode,{next_recommended_mission_type:next,child_mission_auto_authorized:false});return {mission,run:{...run,status:'completed',progress_value:100},execution:{next_recommended_mission_type:next,child_mission_auto_authorized:false}};}

Deno.serve(async(request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});const authError=await requireDashboardAuth(request);if(authError)return authError;try{const body=rec(await parseBody(request));const missionType=txt(body.mission_type_key).toUpperCase(),missionName=txt(body.mission_name),agent=txt(body.assigned_agent),stateCode=txt(body.state_code).toUpperCase()||null;if(!missionType||!missionName||!agent)return json({error:'Mission Type, Mission Name, and Agent are required.'},400);const type=(await db(`command_mission_types?mission_type_key=eq.${encodeURIComponent(missionType)}&enabled=eq.true&select=*`))?.[0];if(!type)return json({error:'Mission type is not enabled.'},400);if(type.state_context_required&&!stateCode)return json({error:'This mission type requires state context.'},400);
  let result:any;if(missionType==='ACQUISITION_DISCOVERY')result=await acquisition(type,missionType,missionName,stateCode!,agent);else if(missionType==='PUBLISHER_DISCOVERY')result=await publisher(type,missionType,missionName,stateCode!,agent);else if(GENERAL_DISCOVERY.has(missionType))result=await genericDiscovery(type,missionType,missionName,stateCode!,agent);else if(missionType==='STATE_MISSION')result=await stateMission(type,missionType,missionName,stateCode!,agent);else return json({error:`${type.display_name} has no authorized runtime adapter.`,code:'RUNTIME_ADAPTER_REQUIRED'},409);if(result?.error)return json({error:result.error},result.status||409);return json(result,202);}catch(error){return json({error:error instanceof Error?error.message:String(error)},500);}}));