import { corsHeaders, db, invoke, json, parseBody } from '../_shared/command.ts';

type JsonRecord = Record<string, unknown>;
const now=()=>new Date().toISOString();
const asRecord=(value:unknown):JsonRecord=>value&&typeof value==='object'&&!Array.isArray(value)?value as JsonRecord:{};
const text=(value:unknown):string=>typeof value==='string'?value.trim():value==null?'':String(value);
function stripHtml(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();}
function absolute(base:string,href:string){try{return new URL(href,base).toString();}catch{return href;}}
async function acquisitionRun(runId:string){const rows=await db(`acquisition_runs?command_run_id=eq.${runId}&select=*&order=created_at.desc&limit=1`);if(!rows?.[0])throw new Error('Acquisition run has not been initialized');return rows[0];}
function embedDetailUrl(row:JsonRecord){const raw=asRecord(row.raw_payload);const platformId=text(raw.platform_project_id);if(platformId)return `https://procurement.opengov.com/portal/embed/tucson-az/projects/${platformId}`;const original=text(row.source_url);return original.includes('/portal/embed/')?original:original.replace('/portal/','/portal/embed/');}
function linksFromHtml(html:string,baseUrl:string){const links=[...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(m=>({url:absolute(baseUrl,m[1]),label:stripHtml(m[2])}));return [...new Map(links.filter(l=>/\.(pdf|docx?|xlsx?|csv|zip)(\?|$)/i.test(l.url)||/(addendum|amendment|attachment|document|specification|scope|bid form|question|answer)/i.test(`${l.label} ${l.url}`)).map(l=>[l.url,l])).values()];}
async function handleDetail(body:JsonRecord){const run=await acquisitionRun(text(body.run_id));const rows=await db(`acquisition_raw_records?acquisition_run_id=eq.${run.id}&is_current_version=eq.true&select=*`);let retrieved=0,failed=0;for(const row of rows){const detailUrl=embedDetailUrl(row);try{const response=await fetch(detailUrl,{redirect:'follow',headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'Mozilla/5.0 (compatible; APROPOS-PDAS/1.0; public procurement retrieval)'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const detail=await response.text();if(!detail||detail.length<500)throw new Error('OpenGov detail response was unexpectedly empty');const raw=asRecord(row.raw_payload);await db(`acquisition_raw_records?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({source_url:detailUrl,raw_payload:{...raw,official_source_url:detailUrl,source_url:detailUrl,__aadp_detail:detail,__aadp_detail_url:detailUrl,__aadp_detail_retrieved_at:now()},detail_retrieved_at:now(),detail_retrieval_status:'SUCCESS',detail_retrieval_error:null})});retrieved++;}catch(error){failed++;await db(`acquisition_raw_records?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({detail_retrieval_status:'FAILED',detail_retrieval_error:error instanceof Error?error.message:String(error)})});}}if(rows.length&&retrieved===0)throw new Error(`OpenGov detail retrieval failed for all ${rows.length} records`);return{success:true,task_type:'PROJECT_DETAIL_RETRIEVAL',metrics:{detail_records_retrieved:retrieved,detail_retrieval_failures:failed},evidence:{acquisition_run_id:run.id,adapter:'OPENGOV_PUBLIC_PORTAL_V4',embed_route:true}};}
async function handleDocumentStage(body:JsonRecord){const run=await acquisitionRun(text(body.run_id));const rows=await db(`acquisition_raw_records?acquisition_run_id=eq.${run.id}&is_current_version=eq.true&select=*`);let manifests=0,documents=0;for(const row of rows){const raw=asRecord(row.raw_payload);const detail=typeof raw.__aadp_detail==='string'?raw.__aadp_detail:'';const entries=linksFromHtml(detail,text(row.source_url));const manifest={documents:entries,addenda:entries.filter(i=>/addend/i.test(i.label)),amendments:entries.filter(i=>/amend/i.test(i.label)),questions_answers:entries.filter(i=>/(question|answer|q&a)/i.test(i.label))};const existing=await db(`aadp_document_manifests?acquisition_run_id=eq.${run.id}&raw_record_id=eq.${row.id}&select=id`);if(existing.length){await db(`aadp_document_manifests?id=eq.${existing[0].id}`,{method:'PATCH',body:JSON.stringify({manifest,document_count:entries.length,retrieved_at:now()})});}else{await db('aadp_document_manifests',{method:'POST',body:JSON.stringify({acquisition_run_id:run.id,raw_record_id:row.id,source_record_id:row.source_record_id,manifest,document_count:entries.length,retrieved_at:now()})});}await db(`acquisition_raw_records?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({document_manifest_count:entries.length,addendum_count:manifest.addenda.length,amendment_count:manifest.amendments.length,public_qa_count:manifest.questions_answers.length})});manifests++;documents+=entries.length;}return{success:true,task_type:text(body.task_type),metrics:{document_manifests:manifests,documents_discovered:documents},evidence:{acquisition_run_id:run.id,adapter:'OPENGOV_PUBLIC_PORTAL_V4',upserted_manifests:manifests}};}
Deno.serve(async(request:Request)=>{if(request.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(request.method!=='POST')return json({error:'Method not allowed'},405);try{const body=asRecord(await parseBody(request));switch(text(body.task_type)){case'PROJECT_DETAIL_RETRIEVAL':return json(await handleDetail(body));case'DOCUMENT_DISCOVERY':case'DOCUMENT_RETRIEVAL':return json(await handleDocumentStage(body));default:return json(await invoke('aadp-publisher-adapter-core',body));}}catch(error){return json({success:false,error:error instanceof Error?error.message:String(error)},500);}});