alter table public.command_tasks drop constraint if exists command_tasks_task_type_check;
alter table public.command_tasks add constraint command_tasks_task_type_check check (task_type = any (array[
'PUBLISHER_DISCOVERY','PUBLISHER_ACCESS_ASSESSMENT','PUBLISHER_REGISTRY_UPDATE','PUBLISHER_ASSIGNMENT_CREATE',
'ACQUISITION_RUN_START','ACQUISITION_PAGE_FETCH','PROJECT_DETAIL_RETRIEVAL','ACQUISITION_RECORD_STORE','ACQUISITION_RUN_CLOSE',
'DOCUMENT_DISCOVERY','DOCUMENT_RETRIEVAL','REQUIREMENT_EXTRACTION','RECORD_NORMALIZATION','RECORD_DEDUPLICATION',
'RECORD_QUALIFICATION','QUALIFIED_RECORD_UPSERT','REJECTION_RECORD_CREATE','PROCUREMENT_LANGUAGE_ANALYSIS','AOIE_BATCH_REVIEW',
'MATCHING_RECOMMENDATION_CREATE','MATCHING_RECOMMENDATION_TEST','RUN_RECONCILIATION','EXECUTIVE_REPORT_CREATE',
'PUBLISHER_ACCESS_REASSESSMENT','TASK_RETRY','TASK_ESCALATION',
'OFFICIAL_SOURCE_RESEARCH','DUPLICATE_CONTROL','CANDIDATE_STAGING','CANDIDATE_REVIEW','STATE_CAPABILITY_EVALUATION','STATE_RECOMMENDATION'
]));