import { corsHeaders, db, json, parseBody, recordEvent, requireDashboardAuth, requireServiceRole } from '../_shared/command.ts';

type J=Record<string,unknown>;
const rec=(v:unknown):J=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:{};
const txt=(v:unknown)=>typeof v==='string'?v.trim():v==null?'':String(v);
const arr=(v:unknown)=>Array.isArray(v)?v:[];

async function authorize(request:Request){const serviceError=requireServiceRole(request);if(!serviceError)return null;return await requireDashboardAuth(request);}
function outputText(data:J){if(typeof data.output_text==='string')return data.output_text;for(const item of arr(data.output)){const r=rec(item);for(const part of arr(r.content)){const p=rec(part);if(p.type==='output_text'&&typeof p.text==='string')return p.text;}}return '';}
function parseJson(raw:string){const cleaned=raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();try{return JSON.parse(cleaned);}catch{const a=cleaned.indexOf('{'),b=cleaned.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(cleaned.slice(a,b+1));throw new Error('Research provider did not return parseable JSON.');}}
const config:Record<string,{registry:string,label:string,criteria:string}>={
  BUSINESS_DEVELOPMENT_DISCOVERY:{registry:'business_development_registry',label:'business-development advisory organizations',criteria:'Identify organizations with a functioning advisory, counseling, accelerator, technical-assistance, or business-growth pathway that APROPOS can legitimately access. A generic economic-development directory page is insufficient.'},
  OPPORTUNITY_PARTNER_DISCOVERY:{registry:'opportunity_partner_registry',label:'procurement opportunity access partners',criteria:'Identify organizations that can expand procurement opportunity access through existing contracting, supplier-development, small-business, referral, training, or community programs.'},
  INSTITUTIONAL_BUYER_DISCOVERY:{registry:'institutional_buyer_registry',label:'institutional buyers and pilot sponsors',criteria:'Identify organizations capable of buying, sponsoring, piloting, licensing, distributing, funding, or strategically supporting APROPOS procurement intelligence. Prioritize active government-contracting or supplier-development programs, identifiable program leadership, funded initiatives, purchasing authority, and measurable participant outcomes.'}
};

async function failRun(commandRunId:string,discoveryRunId:string,message:string){const now=new Date().toISOString();await db(`command_discovery_runs?id=eq.${discoveryRunId}`,{method:'PATCH',body:JSON.stringify({status:'FAILED',current_stage:'RESEARCH_FAILED',completed_at:now,updated_at:now,evidence:{error:message}})});await db(`command_runs?id=eq.${commandRunId}`,{method:'PATCH',body:JSON.stringify({status:'failed',aadp_state:'FAILED',current_stage:'RESEARCH_FAILED',failure_count:1,action_required:true,last_activity_at:now,completed_at:now,result_summary:message})});await db('command_notifications',{method:'POST',body:JSON.stringify({notification_type:'MISSION_FAILURE',severity:'ERROR',title:'Discovery mission requires attention',message,state_code:null,command_run_id:commandRunId,action_required:true,created_at:now})}).catch(()=>null);await recordEvent(commandRunId,null,'DISCOVERY_RESEARCH_FAILED',message,{}).catch(()=>null);}

async function research(commandRunId:string,discoveryRunId:string,missionType:string,stateCode:string,missionName:string){
  const c=config[missionType];if(!c){await failRun(commandRunId,discoveryRunId,'Unsupported generalized discovery mission type.');return;}
  const key=Deno.env.get('OPENAI_API_KEY')||'';if(!key){await failRun(commandRunId,discoveryRunId,'OPENAI_API_KEY is not configured for autonomous official-source research.');return;}
  const model=Deno.env.get('OPENAI_DISCOVERY_MODEL')||'gpt-5.6';const now=new Date().toISOString();
  await db(`command_discovery_runs?id=eq.${discoveryRunId}`,{method:'PATCH',body:JSON.stringify({status:'RUNNING',current_stage:'OFFICIAL_SOURCE_RESEARCH',started_at:now,updated_at:now})});
  await db(`command_runs?id=eq.${commandRunId}`,{method:'PATCH',body:JSON.stringify({status:'running',aadp_state:'RUNNING',current_stage:'OFFICIAL_SOURCE_RESEARCH',progress_mode:'STAGE',progress_value:20,last_activity_at:now})});
  const prompt=`You are the APROPOS autonomous discovery research agent. Mission: ${missionName}. State: ${stateCode}. Research target: ${c.label}. ${c.criteria}\n\nUse web search. Use official organizational or government sources whenever possible. Do not invent organizations, contacts, programs, emails, URLs, authority, funding, or qualification facts. Return up to 8 strong verified candidates. If a fact cannot be verified, use an empty string. source_urls must contain official evidence URLs. prospect_score is 0-100 based only on supported fit evidence.\n\nReturn ONLY valid JSON with this exact shape: {\"candidates\":[{\"organization_name\":\"\",\"organization_type\":\"\",\"official_website\":\"\",\"relevant_program\":\"\",\"qualification_summary\":\"\",\"commercial_fit\":\"\",\"decision_maker_name\":\"\",\"decision_maker_title\":\"\",\"decision_maker_email\":\"\",\"source_urls\":[\"\"],\"prospect_score\":0}]}`;
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,tools:[{type:'web_search',search_context_size:'medium'}],input:prompt})});
  const data=rec(await response.json().catch(()=>({})));if(!response.ok){await failRun(commandRunId,discoveryRunId,`Official-source research provider failed (${response.status}): ${txt(rec(data.error).message)||'unknown error'}`);return;}
  let parsed:J;try{parsed=rec(parseJson(outputText(data)));}catch(e){await failRun(commandRunId,discoveryRunId,e instanceof Error?e.message:String(e));return;}
  const candidates=arr(parsed.candidates).map(rec).filter(x=>txt(x.organization_name));
  const existing=await db(`${c.registry}?state_code=eq.${stateCode}&select=organization_name`);const names=new Set((existing||[]).map((x:any)=>txt(x.organization_name).toLowerCase()));let staged=0,verified=0,duplicates=0;
  for(const x of candidates){const sources=arr(x.source_urls).map(txt).filter(Boolean);const name=txt(x.organization_name);const duplicate=names.has(name.toLowerCase());if(duplicate)duplicates++;const sourceVerified=sources.length>0&&Boolean(txt(x.official_website));if(sourceVerified)verified++;
    await db('command_discovery_candidates',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify({discovery_run_id:discoveryRunId,mission_type_key:missionType,state_code:stateCode,organization_name:name,organization_type:txt(x.organization_type)||null,official_website:txt(x.official_website)||null,relevant_program:txt(x.relevant_program)||null,qualification_summary:txt(x.qualification_summary)||null,commercial_fit:txt(x.commercial_fit)||null,decision_maker_name:txt(x.decision_maker_name)||null,decision_maker_title:txt(x.decision_maker_title)||null,decision_maker_email:txt(x.decision_maker_email)||null,source_urls:sources,source_verified:sourceVerified,duplicate_status:duplicate?'EXISTING_REGISTRY_MATCH':'NO_MATCH',review_status:sourceVerified?'PENDING_REVIEW':'RESEARCH_REQUIRED',prospect_score:Number(x.prospect_score||0),evidence:{provider:'openai_responses_web_search',model}})});staged++;}
  const completedAt=new Date().toISOString();
  await db(`command_discovery_runs?id=eq.${discoveryRunId}`,{method:'PATCH',body:JSON.stringify({status:'PAUSED_FOR_REVIEW',current_stage:'PROJECT_OWNER_APPROVAL_OR_EXCEPTION_REVIEW',result_count:staged,completed_at:completedAt,updated_at:completedAt,evidence:{candidates_staged:staged,official_sources_verified:verified,duplicate_matches:duplicates,human_registry_admission_required:true,provider:'openai_responses_web_search',model}})});
  await db(`command_runs?id=eq.${commandRunId}`,{method:'PATCH',body:JSON.stringify({status:'paused',aadp_state:'PAUSED',current_stage:'CANDIDATE_REVIEW',progress_value:90,last_activity_at:completedAt,completed_at:completedAt,action_required:true,result_summary:`${staged} candidates staged; human registry review required.`,registry_impact:{candidates_staged:staged,registry_records_created:0}})});
  await db('command_notifications',{method:'POST',body:JSON.stringify({notification_type:'MISSION_ACTION_REQUIRED',severity:'INFO',title:`${missionName}: candidate review required`,message:`${staged} candidates were researched and staged; ${verified} contain official-source evidence.`,state_code:stateCode,command_run_id:commandRunId,action_required:true,created_at:completedAt})}).catch(()=>null);
  await recordEvent(commandRunId,null,'DISCOVERY_RESEARCH_COMPLETE','Official-source discovery research completed and candidates were staged',{candidates_staged:staged,official_sources_verified:verified,duplicate_matches:duplicates});
}

Deno.serve(async(request:Request)=>{
  if(request.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});const authError=await authorize(request);if(authError)return authError;if(request.method!=='POST')return json({error:'Method not allowed'},405);
  try{const body=rec(await parseBody(request));const commandRunId=txt(body.command_run_id),missionType=txt(body.mission_type_key).toUpperCase(),stateCode=txt(body.state_code).toUpperCase(),missionName=txt(body.mission_name)||`${stateCode} ${missionType}`;if(!commandRunId||!config[missionType]||!/^[A-Z]{2}$/.test(stateCode))return json({error:'command_run_id, supported mission_type_key, and state_code are required'},400);
    const existing=await db(`command_discovery_runs?command_run_id=eq.${commandRunId}&select=*`);const dr=existing?.[0]||(await db('command_discovery_runs',{method:'POST',body:JSON.stringify({command_run_id:commandRunId,mission_type_key:missionType,state_code:stateCode,status:'QUEUED',current_stage:'QUEUED',research_query:missionName,evidence:{source:'EXECUTIVE_COMMAND_CENTER'}})}))[0];
    EdgeRuntime.waitUntil(research(commandRunId,dr.id,missionType,stateCode,missionName));return json({command_run_id:commandRunId,discovery_run_id:dr.id,status:'QUEUED',asynchronous:true},202);
  }catch(error){return json({error:error instanceof Error?error.message:String(error)},500);}
});